name: Question
description: Ask a question about using xcfreader or ui-xcfimage
title: "[Question]: "
labels: ["question"]
body:
  - type: markdown
    attributes:
      value: |
        Have a question? We're here to help! Please check the [documentation](https://github.com/andimclean/xcfreader#readme) and [troubleshooting guide](https://github.com/andimclean/xcfreader/blob/master/TROUBLESHOOTING.md) first.

  - type: dropdown
    id: package
    attributes:
      label: Package
      description: Which package is your question about?
      options:
        - xcfreader (core parser library)
        - ui-xcfimage (web component)
        - General
        - Not sure
    validations:
      required: true

  - type: textarea
    id: question
    attributes:
      label: Your Question
      description: What would you like to know?
      placeholder: How do I...?
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Context
      description: Please provide any relevant context about what you're trying to accomplish
      placeholder: I'm trying to build...
    validations:
      required: false

  - type: textarea
    id: attempted
    attributes:
      label: What Have You Tried?
      description: What have you already attempted?
      placeholder: |
        - I tried...
        - I looked at...
        - I read...
    validations:
      required: false

  - type: textarea
    id: code
    attributes:
      label: Code Sample
      description: If applicable, please share relevant code
      render: typescript
    validations:
      required: false

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission Checklist
      options:
        - label: I have checked the documentation
          required: true
        - label: I have searched existing issues and discussions
          required: true
